const E=id=>document.getElementById(id),C=E('box'),ctx=C.getContext('2d'),temp=E('temp'),ea=E('ea'),na=E('na'),nb=E('nb');let p=[],paused=false,last=performance.now(),collisions=0,reactions=0,cHist=[],rHist=[];
function randVel(scale){const a=Math.random()*Math.PI*2,m=scale*(.45+Math.random()*.9);return[Math.cos(a)*m,Math.sin(a)*m]}
function reset(){p=[];const T=+temp.value,scale=Math.sqrt(T/300)*62;for(const [type,n] of [['A',+na.value],['B',+nb.value]])for(let i=0;i<n;i++){const v=randVel(scale);p.push({type,x:18+Math.random()*(C.width-36),y:18+Math.random()*(C.height-36),vx:v[0],vy:v[1],r:5})}collisions=0;reactions=0;cHist=[];rHist=[];labels()}
function labels(){E('tv').textContent=temp.value+' K';E('eav').textContent=(+ea.value).toFixed(2)+' arb';E('nav').textContent=na.value;E('nbv').textContent=nb.value}
function rescale(){const target=Math.sqrt(+temp.value/300)*62;let rms=Math.sqrt(p.reduce((s,a)=>s+a.vx*a.vx+a.vy*a.vy,0)/Math.max(1,p.length));if(rms<1)return;const f=target/rms;for(const a of p){a.vx*=f;a.vy*=f}}
function step(dt){for(const a of p){a.x+=a.vx*dt;a.y+=a.vy*dt;if(a.x<a.r){a.x=a.r;a.vx=Math.abs(a.vx)}if(a.x>C.width-a.r){a.x=C.width-a.r;a.vx=-Math.abs(a.vx)}if(a.y<a.r){a.y=a.r;a.vy=Math.abs(a.vy)}if(a.y>C.height-a.r){a.y=C.height-a.r;a.vy=-Math.abs(a.vy)}}const dead=new Set(),born=[];for(let i=0;i<p.length;i++){if(dead.has(i))continue;for(let j=i+1;j<p.length;j++){if(dead.has(j))continue;const a=p[i],b=p[j],dx=b.x-a.x,dy=b.y-a.y,d2=dx*dx+dy*dy,rr=a.r+b.r;if(d2>rr*rr||d2<1e-8)continue;collisions++;const d=Math.sqrt(d2),nx=dx/d,ny=dy/d,rvx=b.vx-a.vx,rvy=b.vy-a.vy,rel=rvx*nx+rvy*ny;if(rel<0){a.vx+=rel*nx;a.vy+=rel*ny;b.vx-=rel*nx;b.vy-=rel*ny}const reactive=(a.type!==b.type&&a.type!=='C'&&b.type!=='C');const eRel=.5*(rvx*rvx+rvy*rvy)/4000;if(reactive&&eRel>+ea.value){dead.add(i);dead.add(j);reactions++;born.push({type:'C',x:(a.x+b.x)/2,y:(a.y+b.y)/2,vx:(a.vx+b.vx)/2,vy:(a.vy+b.vy)/2,r:7});break}}}if(dead.size)p=p.filter((_,i)=>!dead.has(i)).concat(born)}
function draw(){ctx.fillStyle='#f7f5ef';ctx.fillRect(0,0,C.width,C.height);for(const a of p){ctx.fillStyle=a.type==='A'?'#7865d5':a.type==='B'?'#df7f50':'#50ad7a';ctx.beginPath();ctx.arc(a.x,a.y,a.r,0,Math.PI*2);ctx.fill()}ctx.fillStyle='#666';ctx.font='13px system-ui';ctx.fillText('C ürünleri: '+p.filter(x=>x.type==='C').length,16,24)}
let statT=0,lastC=0,lastR=0;function stats(dt){statT+=dt;if(statT>=1){const dc=collisions-lastC,dr=reactions-lastR;lastC=collisions;lastR=reactions;E('coll').textContent=dc;E('rate').textContent=dr;E('frac').textContent=dc?Math.round(dr/dc*100)+'%':'0%';E('prod').textContent=p.filter(x=>x.type==='C').length;statT=0}}
function loop(now){const dt=Math.min(.03,(now-last)/1000);last=now;if(!paused){step(dt);stats(dt)}draw();requestAnimationFrame(loop)}
temp.oninput=()=>{labels();rescale()};ea.oninput=labels;na.oninput=reset;nb.oninput=reset;E('pause').onclick=()=>{paused=!paused;E('pause').textContent=paused?'Devam et':'Duraklat'};E('reset').onclick=reset;reset();requestAnimationFrame(loop);