const E=id=>document.getElementById(id),C=E('net'),ctx=C.getContext('2d'),lr=E('lr');const data=[[0,0,0],[0,1,1],[1,0,1],[1,1,0]];let W1,b1,W2,b2,epoch=0,selected=1,auto=false,last=performance.now(),lastGrad=0;
const sig=x=>1/(1+Math.exp(-x));
function rnd(){return(Math.random()-.5)*2}
function reset(){W1=Array.from({length:3},()=>[rnd(),rnd()]);b1=[rnd(),rnd(),rnd()];W2=[rnd(),rnd(),rnd()];b2=rnd();epoch=0;lastGrad=0;ui()}
function forward(x){const h=W1.map((w,j)=>sig(w[0]*x[0]+w[1]*x[1]+b1[j])),o=sig(W2.reduce((s,w,j)=>s+w*h[j],b2));return{h,o}}
function lossAll(){let L=0;for(const [x1,x2,y] of data){const o=forward([x1,x2]).o;L+=-(y*Math.log(o+1e-9)+(1-y)*Math.log(1-o+1e-9))}return L/data.length}
function train(){let gW1=Array.from({length:3},()=>[0,0]),gb1=[0,0,0],gW2=[0,0,0],gb2=0;for(const [x1,x2,y] of data){const x=[x1,x2],{h,o}=forward(x),d2=o-y;for(let j=0;j<3;j++){gW2[j]+=d2*h[j];const d1=W2[j]*d2*h[j]*(1-h[j]);gb1[j]+=d1;gW1[j][0]+=d1*x1;gW1[j][1]+=d1*x2}gb2+=d2}const n=data.length,rate=+lr.value;let norm=gb2*gb2;for(let j=0;j<3;j++){gW2[j]/=n;gb1[j]/=n;norm+=gW2[j]*gW2[j]+gb1[j]*gb1[j];for(let i=0;i<2;i++){gW1[j][i]/=n;norm+=gW1[j][i]*gW1[j][i];W1[j][i]-=rate*gW1[j][i]}W2[j]-=rate*gW2[j];b1[j]-=rate*gb1[j]}b2-=rate*gb2/n;lastGrad=Math.sqrt(norm);epoch++;ui()}
function ui(){E('lrv').textContent=(+lr.value).toFixed(2);E('loss').textContent=lossAll().toFixed(4);E('epoch').textContent=epoch;E('out').textContent=forward(data[selected]).o.toFixed(3);E('grad').textContent=lastGrad.toFixed(4)}
function line(a,b,w){ctx.strokeStyle=w>=0?'rgba(76,118,218,.72)':'rgba(220,83,78,.72)';ctx.lineWidth=1+Math.min(10,Math.abs(w)*4);ctx.beginPath();ctx.moveTo(...a);ctx.lineTo(...b);ctx.stroke()}
function node(x,y,a,label){ctx.fillStyle=`rgb(${Math.round(245-120*a)},${Math.round(245-85*a)},${Math.round(250-15*a)})`;ctx.strokeStyle='#333';ctx.lineWidth=2;ctx.beginPath();ctx.arc(x,y,28,0,Math.PI*2);ctx.fill();ctx.stroke();ctx.fillStyle='#222';ctx.font='700 12px system-ui';ctx.textAlign='center';ctx.fillText(label,x,y-35);ctx.fillText(a.toFixed(2),x,y+4)}
function draw(){ctx.fillStyle='#fafaf7';ctx.fillRect(0,0,C.width,C.height);const ex=data[selected],f=forward(ex),inp=[[170,165],[170,325]],hid=[[450,105],[450,245],[450,385]],out=[730,245];for(let j=0;j<3;j++){line(inp[0],hid[j],W1[j][0]);line(inp[1],hid[j],W1[j][1]);line(hid[j],out,W2[j])}node(inp[0][0],inp[0][1],ex[0],'x₁');node(inp[1][0],inp[1][1],ex[1],'x₂');for(let j=0;j<3;j++)node(hid[j][0],hid[j][1],f.h[j],'h'+(j+1));node(out[0],out[1],f.o,'ŷ');
 const y=data[selected][2];ctx.fillStyle='#555';ctx.font='700 15px system-ui';ctx.fillText('hedef y = '+y,out[0],out[1]+58);
 const boxY=455;for(let i=0;i<4;i++){const x=250+i*110;ctx.fillStyle=i===selected?'#222':'#ecebe5';ctx.beginPath();ctx.roundRect(x-45,boxY-22,90,44,12);ctx.fill();ctx.fillStyle=i===selected?'#fff':'#333';ctx.font='700 13px system-ui';ctx.fillText(data[i][0]+' XOR '+data[i][1]+' → '+data[i][2],x,boxY+5)}}
C.onclick=e=>{const r=C.getBoundingClientRect(),x=(e.clientX-r.left)*C.width/r.width,y=(e.clientY-r.top)*C.height/r.height;if(y>420){selected=Math.max(0,Math.min(3,Math.round((x-250)/110)));ui()}};E('step').onclick=train;E('auto').onclick=()=>{auto=!auto;E('auto').textContent=auto?'Durdur':'Otomatik'};E('reset').onclick=reset;lr.oninput=ui;function loop(now){if(auto&&now-last>35){train();last=now}draw();requestAnimationFrame(loop)}reset();requestAnimationFrame(loop);