const E=id=>document.getElementById(id),R=E('rod'),rc=R.getContext('2d'),P=E('plot'),pc=P.getContext('2d'),alpha=E('alpha'),width=E('width'),speed=E('speed');
window.mathFormulas={f1:'\\rho cA\\,dx\\,\\frac{\\partial T}{\\partial t}=Aq(x)-Aq(x+dx)',f2:'q=-k\\frac{\\partial T}{\\partial x}\\quad\\Rightarrow\\quad \\rho c\\frac{\\partial T}{\\partial t}=k\\frac{\\partial^2T}{\\partial x^2}',f3:'\\frac{\\partial T}{\\partial t}=\\alpha\\frac{\\partial^2T}{\\partial x^2},\\qquad \\alpha=\\frac{k}{\\rho c}',f4:'T_i^{n+1}=T_i^n+r(T_{i+1}^n-2T_i^n+T_{i-1}^n),\\qquad r=\\frac{\\alpha\\Delta t}{\\Delta x^2}',f5:'0<r\\le\\frac12'};
const N=161,dx=1/(N-1);let u,u0,t=0,last=performance.now(),paused=false;
function init(){const w=+width.value;u=Array.from({length:N},(_,i)=>{const x=i*dx;return Math.exp(-.5*Math.pow((x-.5)/w,2))});u[0]=u[N-1]=0;u0=[...u];t=0;labels()}
function labels(){E('av').textContent=(+alpha.value).toFixed(2);E('wv').textContent=(+width.value).toFixed(2);E('sv').textContent=(+speed.value).toFixed(1)+'×'}
function advance(real){const a=+alpha.value,dt=.45*dx*dx/a,target=real*+speed.value,steps=Math.min(1800,Math.ceil(target/dt));for(let s=0;s<steps;s++){const v=[...u];for(let i=1;i<N-1;i++)v[i]=u[i]+.45*(u[i+1]-2*u[i]+u[i-1]);v[0]=v[N-1]=0;u=v;t+=dt}}
function heat(){let sum=0;for(let i=0;i<N;i++)sum+=u[i];return sum*dx}
function cmap(z){z=Math.max(0,Math.min(1,z));const r=Math.round(245*z+25*(1-z)),g=Math.round(95*z+55*(1-z)),b=Math.round(55*z+105*(1-z));return 'rgb('+r+','+g+','+b+')'}
function draw(){rc.fillStyle='#f7f6f1';rc.fillRect(0,0,R.width,R.height);const y=70,h=80,w=R.width-80,x0=40;for(let i=0;i<N-1;i++){rc.fillStyle=cmap(u[i]);rc.fillRect(x0+i/(N-1)*w,y,w/(N-1)+1,h)}rc.strokeStyle='#333';rc.strokeRect(x0,y,w,h);rc.fillStyle='#777';rc.font='13px system-ui';rc.fillText('T=0',x0-4,y+h+25);rc.fillText('T=0',x0+w-22,y+h+25);
pc.fillStyle='#fafaf7';pc.fillRect(0,0,P.width,P.height);pc.strokeStyle='#deddd5';pc.beginPath();pc.moveTo(48,P.height-40);pc.lineTo(P.width-20,P.height-40);pc.moveTo(48,20);pc.lineTo(48,P.height-40);pc.stroke();const drawLine=(arr,col,dash)=>{pc.setLineDash(dash||[]);pc.strokeStyle=col;pc.lineWidth=2.5;pc.beginPath();arr.forEach((v,i)=>{const x=48+i/(N-1)*(P.width-70),y=P.height-40-v*(P.height-70);if(i)pc.lineTo(x,y);else pc.moveTo(x,y)});pc.stroke();pc.setLineDash([])};drawLine(u0,'#bbb',[6,5]);drawLine(u,'#6f5bd3',[]);
E('tv').textContent=t.toFixed(4);E('rv').textContent='0.450';E('maxv').textContent=Math.max(...u).toFixed(3);E('heat').textContent=heat().toFixed(3)}
function loop(now){const dt=Math.min(.05,(now-last)/1000);last=now;if(!paused)advance(dt);draw();requestAnimationFrame(loop)}
[alpha,speed].forEach(el=>el.oninput=labels);width.oninput=()=>{labels();init()};E('reset').onclick=init;E('pause').onclick=()=>{paused=!paused;E('pause').textContent=paused?'Devam et':'Duraklat'};init();requestAnimationFrame(loop);