const C=document.getElementById('game'),ctx=C.getContext('2d'),E=id=>document.getElementById(id),T=80,COLS=12,ROWS=8,dirs={U:[0,-1],D:[0,1],L:[-1,0],R:[1,0],W:[0,0]};
const levels=[
 {start:[1,6],file:[6,2],exit:[10,1],walls:[[3,1],[3,2],[3,3],[7,4],[7,5],[7,6]],guards:[[[5,5],[6,5],[6,4],[5,4]],[[9,2],[9,3],[8,3],[8,2]]]},
 {start:[1,1],file:[9,6],exit:[10,1],walls:[[4,0],[4,1],[4,2],[4,4],[4,5],[4,6],[7,2],[7,3],[7,4],[7,5]],guards:[[[2,5],[3,5],[3,6],[2,6]],[[6,1],[7,1],[8,1],[8,2],[7,2],[6,2]]]},
 {start:[1,6],file:[10,6],exit:[10,1],walls:[[2,3],[3,3],[4,3],[6,3],[7,3],[8,3],[9,3]],guards:[[[5,1],[6,1],[6,2],[5,2]],[[3,5],[4,5],[5,5],[4,5]],[[8,6],[8,5],[9,5],[9,6]]]},
 {start:[6,6],file:[1,1],exit:[10,1],walls:[[3,2],[3,3],[3,4],[6,1],[6,2],[8,4],[8,5],[8,6]],guards:[[[1,5],[2,5],[2,4],[1,4]],[[5,4],[6,4],[7,4],[7,3],[6,3],[5,3]],[[9,2],[10,2],[10,3],[9,3]]]},
 {start:[1,4],file:[10,4],exit:[6,1],walls:[[3,1],[3,2],[3,5],[3,6],[6,3],[6,4],[8,1],[8,2],[8,5],[8,6]],guards:[[[2,1],[2,2],[2,3],[1,3]],[[5,6],[6,6],[7,6],[7,5]],[[9,3],[10,3],[10,4],[9,4]],[[5,1],[6,1],[7,1],[6,1]]]}
];
let li=0,s;function L(){return levels[li]}function key(p){return p[0]+','+p[1]}function wall(x,y){return x<0||y<0||x>=COLS||y>=ROWS||L().walls.some(w=>w[0]===x&&w[1]===y)}
function reset(){s={p:[...L().start],has:false,alarm:0,guards:L().guards.map(path=>({path,i:0})),won:false};E('next').disabled=true;E('status').textContent='Her hamleden sonra görevliler ilerler. Duvarlar görüşü keser.';ui()}
function ui(){E('level').textContent=(li+1)+'/'+levels.length;E('file').textContent=s.has?'alındı':'yok';E('alarm').textContent=s.alarm}
function guardPos(g){return g.path[g.i%g.path.length]}function los(a,b){if(a[0]===b[0]){const x=a[0],lo=Math.min(a[1],b[1])+1,hi=Math.max(a[1],b[1]);for(let y=lo;y<hi;y++)if(wall(x,y))return false;return true}if(a[1]===b[1]){const y=a[1],lo=Math.min(a[0],b[0])+1,hi=Math.max(a[0],b[0]);for(let x=lo;x<hi;x++)if(wall(x,y))return false;return true}return false}
function seen(){return s.guards.some(g=>los(guardPos(g),s.p))}
function act(a){if(s.won)return;const d=dirs[a],np=[s.p[0]+d[0],s.p[1]+d[1]];if(!wall(...np))s.p=np;if(key(s.p)===key(L().file)&&!s.has){s.has=true;E('status').textContent='Dosya sende. Şimdi yeşil çıkışa dön.'}
 s.guards.forEach(g=>g.i=(g.i+1)%g.path.length);if(seen()){s.alarm++;E('status').textContent='Görüldün. İkinci alarmda başlangıca geri atılırsın.';if(s.alarm>=2){s.alarm=0;s.p=[...L().start];E('status').textContent='Alarm! Başlangıca geri döndün; dosya sende kalır.'}}
 if(s.has&&key(s.p)===key(L().exit)){s.won=true;E('status').textContent=li===levels.length-1?'Tüm gece vardiyaları temiz.':'Bölüm tamamlandı.';E('next').disabled=li===levels.length-1}ui();draw()}
function draw(){ctx.fillStyle='#edece7';ctx.fillRect(0,0,C.width,C.height);ctx.strokeStyle='#d2d0c9';for(let x=0;x<=COLS;x++){ctx.beginPath();ctx.moveTo(x*T,0);ctx.lineTo(x*T,C.height);ctx.stroke()}for(let y=0;y<=ROWS;y++){ctx.beginPath();ctx.moveTo(0,y*T);ctx.lineTo(C.width,y*T);ctx.stroke()}
 for(const [x,y] of L().walls){ctx.fillStyle='#36363a';ctx.beginPath();ctx.roundRect(x*T+7,y*T+7,T-14,T-14,16);ctx.fill()}
 const file=L().file;if(!s.has){ctx.fillStyle='#e6b84d';ctx.beginPath();ctx.roundRect(file[0]*T+23,file[1]*T+26,34,28,6);ctx.fill()}
 const ex=L().exit;ctx.strokeStyle=s.has?'#58bd83':'#aaa';ctx.lineWidth=5;ctx.strokeRect(ex[0]*T+17,ex[1]*T+17,46,46);
 s.guards.forEach(g=>{const p=guardPos(g);ctx.strokeStyle='rgba(219,71,71,.25)';ctx.lineWidth=16;for(const d of [[1,0],[-1,0],[0,1],[0,-1]]){let x=p[0],y=p[1];ctx.beginPath();ctx.moveTo(x*T+40,y*T+40);while(!wall(x+d[0],y+d[1])){x+=d[0];y+=d[1]}ctx.lineTo(x*T+40,y*T+40);ctx.stroke()}ctx.fillStyle='#c64f4f';ctx.beginPath();ctx.arc(p[0]*T+40,p[1]*T+40,17,0,Math.PI*2);ctx.fill()});
 ctx.fillStyle='#212126';ctx.beginPath();ctx.arc(s.p[0]*T+40,s.p[1]*T+40,19,0,Math.PI*2);ctx.fill();ctx.fillStyle='#fff';ctx.beginPath();ctx.arc(s.p[0]*T+34,s.p[1]*T+35,3,0,Math.PI*2);ctx.arc(s.p[0]*T+46,s.p[1]*T+35,3,0,Math.PI*2);ctx.fill()}
addEventListener('keydown',e=>{const a={ArrowUp:'U',w:'U',W:'U',ArrowDown:'D',s:'D',S:'D',ArrowLeft:'L',a:'L',A:'L',ArrowRight:'R',d:'R',D:'R',' ':'W'}[e.key];if(a){e.preventDefault();act(a)}});document.querySelectorAll('[data-act]').forEach(b=>b.onclick=()=>act(b.dataset.act));E('restart').onclick=reset;E('next').onclick=()=>{if(s.won&&li<levels.length-1){li++;reset()}};reset();draw();