const E=id=>document.getElementById(id),P=E('plot'),pc=P.getContext('2d'),G=E('people'),gc=G.getContext('2d'),R=E('reffplot'),rc=R.getContext('2d'),beta=E('beta'),gamma=E('gamma'),i0=E('i0');
window.mathFormulas={f1:'\\frac{dS}{dt}=-\\beta SI',f2:'\\frac{dI}{dt}=\\beta SI-\\gamma I,\\qquad \\frac{dR}{dt}=\\gamma I',f3:'\\frac{d}{dt}(S+I+R)=0',f4:'\\frac{dI}{dt}\\approx(\\beta S_0-\\gamma)I',f5:'R_0=\\frac{\\beta}{\\gamma},\\qquad R_{eff}(t)=R_0S(t)',f6:'\\beta S-\\gamma=0\\quad\\Rightarrow\\quad S_{peak}=\\frac{\\gamma}{\\beta}=\\frac1{R_0}'};
let data=[];function pars(){return{b:+beta.value,g:+gamma.value,i:+i0.value}}
function reset(){const q=pars(),dt=.05,T=120;let s=1-q.i,i=q.i,r=0;data=[[0,s,i,r]];for(let n=1;n<=T/dt;n++){const f=(S,I,R)=>[-q.b*S*I,q.b*S*I-q.g*I,q.g*I],k1=f(s,i,r),k2=f(s+k1[0]*dt/2,i+k1[1]*dt/2,r+k1[2]*dt/2),k3=f(s+k2[0]*dt/2,i+k2[1]*dt/2,r+k2[2]*dt/2),k4=f(s+k3[0]*dt,i+k3[1]*dt,r+k3[2]*dt);s+=dt*(k1[0]+2*k2[0]+2*k3[0]+k4[0])/6;i+=dt*(k1[1]+2*k2[1]+2*k3[1]+k4[1])/6;r+=dt*(k1[2]+2*k2[2]+2*k3[2]+k4[2])/6;data.push([n*dt,s,i,r])}labels();draw()}
function labels(){const q=pars(),R0=q.b/q.g,peak=data.reduce((a,b)=>b[2]>a[2]?b:a,data[0]),end=data[data.length-1];E('bv').textContent=q.b.toFixed(2);E('gv').textContent=q.g.toFixed(2);E('iv').textContent=q.i.toFixed(3);E('r0v').textContent=R0.toFixed(2);E('reff').textContent=(R0*(1-q.i)).toFixed(2);E('peak').textContent=(peak[2]*100).toFixed(1)+'%';E('peakt').textContent=peak[0].toFixed(1);E('finals').textContent=(end[1]*100).toFixed(1)+'%';E('finalr').textContent=(end[3]*100).toFixed(1)+'%'}
function axes(c,W,H){c.fillStyle='#fafaf7';c.fillRect(0,0,W,H);c.strokeStyle='#deddd5';c.beginPath();c.moveTo(48,H-38);c.lineTo(W-18,H-38);c.moveTo(48,18);c.lineTo(48,H-38);c.stroke()}
function draw(){axes(pc,P.width,P.height);const T=data[data.length-1][0],cols=['#7865d5','#df7a52','#4aa276'];for(let idx=1;idx<=3;idx++){pc.strokeStyle=cols[idx-1];pc.lineWidth=2.5;pc.beginPath();data.forEach((p,n)=>{const x=48+p[0]/T*(P.width-70),y=P.height-38-p[idx]*(P.height-62);if(n)pc.lineTo(x,y);else pc.moveTo(x,y)});pc.stroke()}
const mid=data[Math.floor(data.length*.34)],counts=[Math.round(mid[1]*300),Math.round(mid[2]*300),0];counts[2]=300-counts[0]-counts[1];gc.fillStyle='#f3f0e9';gc.fillRect(0,0,G.width,G.height);let index=0;for(let group=0;group<3;group++)for(let n=0;n<counts[group];n++){const col=index%25,row=Math.floor(index/25),x=18+col*27,y=24+row*27;gc.fillStyle=cols[group];gc.beginPath();gc.arc(x,y,7,0,Math.PI*2);gc.fill();index++}
axes(rc,R.width,R.height);const R0=+beta.value/+gamma.value;rc.strokeStyle='#555';rc.setLineDash([5,5]);const y1=R.height-38-1/Math.max(1.2,R0)*(R.height-62);rc.beginPath();rc.moveTo(48,y1);rc.lineTo(R.width-18,y1);rc.stroke();rc.setLineDash([]);rc.strokeStyle='#d36f52';rc.lineWidth=2.5;rc.beginPath();data.forEach((p,n)=>{const x=48+p[0]/T*(R.width-70),val=R0*p[1],y=R.height-38-val/Math.max(1.2,R0)*(R.height-62);if(n)rc.lineTo(x,y);else rc.moveTo(x,y)});rc.stroke()}
[beta,gamma,i0].forEach(el=>el.oninput=reset);reset();