const E=id=>document.getElementById(id),C=E('scene'),ctx=C.getContext('2d'),A=E('angles'),ac=A.getContext('2d'),S=E('sep'),sc=S.getContext('2d');
const m1=E('m1'),m2=E('m2'),l1=E('l1'),l2=E('l2'),a1=E('a1'),a2=E('a2');let st,shadow,hist,last=performance.now(),paused=false,E0=0,simTime=0;
window.mathFormulas={
f1:'T=\\tfrac12(m_1+m_2)l_1^2\\dot\\theta_1^2+\\tfrac12m_2l_2^2\\dot\\theta_2^2+m_2l_1l_2\\dot\\theta_1\\dot\\theta_2\\cos(\\theta_1-\\theta_2),\\quad V=-(m_1+m_2)gl_1\\cos\\theta_1-m_2gl_2\\cos\\theta_2',
f2:'\\frac{d}{dt}\\frac{\\partial L}{\\partial\\dot\\theta_i}-\\frac{\\partial L}{\\partial\\theta_i}=0',
f3:'(m_1+m_2)l_1\\ddot\\theta_1+m_2l_2\\ddot\\theta_2\\cos\\Delta+m_2l_2\\dot\\theta_2^2\\sin\\Delta+(m_1+m_2)g\\sin\\theta_1=0',
f4:'l_2\\ddot\\theta_2+l_1\\ddot\\theta_1\\cos\\Delta-l_1\\dot\\theta_1^2\\sin\\Delta+g\\sin\\theta_2=0,\\qquad \\Delta=\\theta_1-\\theta_2',
f5:'E=T+V=\\text{constant}'
};
function p(){return{m1:+m1.value,m2:+m2.value,l1:+l1.value,l2:+l2.value,g:9.81}}
function deriv(y){const q=p(),t1=y[0],w1=y[1],t2=y[2],w2=y[3],d=t1-t2,den=2*q.m1+q.m2-q.m2*Math.cos(2*d);const aa1=(-q.g*(2*q.m1+q.m2)*Math.sin(t1)-q.m2*q.g*Math.sin(t1-2*t2)-2*Math.sin(d)*q.m2*(w2*w2*q.l2+w1*w1*q.l1*Math.cos(d)))/(q.l1*den);const aa2=(2*Math.sin(d)*(w1*w1*q.l1*(q.m1+q.m2)+q.g*(q.m1+q.m2)*Math.cos(t1)+w2*w2*q.l2*q.m2*Math.cos(d)))/(q.l2*den);return[w1,aa1,w2,aa2]}
function rk(y,h){const k1=deriv(y),y2=y.map((v,i)=>v+k1[i]*h/2),k2=deriv(y2),y3=y.map((v,i)=>v+k2[i]*h/2),k3=deriv(y3),y4=y.map((v,i)=>v+k3[i]*h),k4=deriv(y4);return y.map((v,i)=>v+h*(k1[i]+2*k2[i]+2*k3[i]+k4[i])/6)}
function energy(y){const q=p(),t1=y[0],w1=y[1],t2=y[2],w2=y[3],d=t1-t2;const T=.5*(q.m1+q.m2)*q.l1*q.l1*w1*w1+.5*q.m2*q.l2*q.l2*w2*w2+q.m2*q.l1*q.l2*w1*w2*Math.cos(d),V=-(q.m1+q.m2)*q.g*q.l1*Math.cos(t1)-q.m2*q.g*q.l2*Math.cos(t2);return T+V}
function reset(){st=[+a1.value*Math.PI/180,0,+a2.value*Math.PI/180,0];shadow=[st[0]+.3*Math.PI/180,0,st[2],0];hist=[];simTime=0;E0=energy(st);last=performance.now();labels()}
function labels(){E('m1v').textContent=(+m1.value).toFixed(1);E('m2v').textContent=(+m2.value).toFixed(1);E('l1v').textContent=(+l1.value).toFixed(1);E('l2v').textContent=(+l2.value).toFixed(1);E('a1v').textContent=a1.value;E('a2v').textContent=a2.value}
function step(dt){const n=Math.max(1,Math.ceil(dt/.006)),h=dt/n;for(let z=0;z<n;z++){st=rk(st,h);shadow=rk(shadow,h)}simTime+=dt;const d=Math.hypot(st[0]-shadow[0],st[2]-shadow[2]);hist.push([simTime,st[0],st[2],d]);if(hist.length>800)hist.shift();E('tv').textContent=simTime.toFixed(2)+' s';const en=energy(st);E('energy').textContent=en.toFixed(3)+' J';E('drift').textContent=((en-E0)/(Math.abs(E0)+1e-9)*100).toFixed(3)+'%';E('delta').textContent=(d*180/Math.PI).toFixed(2)+'°'}
function drawPend(y,color,alpha){const q=p(),scale=120,x0=450,y0=90,x1=x0+Math.sin(y[0])*q.l1*scale,y1=y0+Math.cos(y[0])*q.l1*scale,x2=x1+Math.sin(y[2])*q.l2*scale,y2=y1+Math.cos(y[2])*q.l2*scale;ctx.globalAlpha=alpha;ctx.strokeStyle=color;ctx.lineWidth=6;ctx.beginPath();ctx.moveTo(x0,y0);ctx.lineTo(x1,y1);ctx.lineTo(x2,y2);ctx.stroke();ctx.fillStyle=color;ctx.beginPath();ctx.arc(x1,y1,15,0,Math.PI*2);ctx.fill();ctx.beginPath();ctx.arc(x2,y2,18,0,Math.PI*2);ctx.fill();ctx.globalAlpha=1}
function graph(c,W,H,idx,color,logMode){c.fillStyle='#fafaf7';c.fillRect(0,0,W,H);if(hist.length<2)return;const t0=hist[0][0],t1=hist[hist.length-1][0],vals=hist.map(h=>logMode?Math.log10(Math.max(1e-6,h[idx])):h[idx]),mx=Math.max(.1,...vals.map(Math.abs));c.strokeStyle=color;c.lineWidth=2.5;c.beginPath();hist.forEach((h,i)=>{const x=45+(h[0]-t0)/Math.max(.1,t1-t0)*(W-65),v=logMode?Math.log10(Math.max(1e-6,h[idx])):h[idx],y=H/2-v/mx*(H*.4);if(i)c.lineTo(x,y);else c.moveTo(x,y)});c.stroke()}
function draw(){ctx.fillStyle='#faf8f0';ctx.fillRect(0,0,C.width,C.height);ctx.fillStyle='#ded9cd';ctx.fillRect(360,60,180,20);drawPend(shadow,'#d7a0ad',.35);drawPend(st,'#2d2d35',1);graph(ac,A.width,A.height,1,'#7963d8',false);if(hist.length>2){const t0=hist[0][0],t1=hist[hist.length-1][0],mx=Math.max(.1,...hist.flatMap(h=>[Math.abs(h[1]),Math.abs(h[2])]));ac.strokeStyle='#df815d';ac.lineWidth=2;ac.beginPath();hist.forEach((h,i)=>{const x=45+(h[0]-t0)/Math.max(.1,t1-t0)*(A.width-65),y=A.height/2-h[2]/mx*(A.height*.4);if(i)ac.lineTo(x,y);else ac.moveTo(x,y)});ac.stroke()}graph(sc,S.width,S.height,3,'#4b9a6f',true)}
function loop(now){const dt=Math.min(.025,(now-last)/1000);last=now;if(!paused)step(dt);draw();requestAnimationFrame(loop)}
[m1,m2,l1,l2,a1,a2].forEach(x=>x.oninput=()=>{labels();reset()});E('pause').onclick=()=>{paused=!paused;E('pause').textContent=paused?'Devam et':'Duraklat'};E('reset').onclick=reset;reset();requestAnimationFrame(loop);