const E=id=>document.getElementById(id),C=E('climate'),ctx=C.getContext('2d'),F=E('flux'),fc=F.getContext('2d'),solar=E('solar'),albedo=E('albedo'),eps=E('eps'),cap=E('cap'),ice=E('ice');const sigma=5.670374419e-8;let T=288,t=0,hist=[],paused=false,last=performance.now();
function alphaEff(){const a=+albedo.value;if(!ice.checked)return a;return Math.min(.82,a+.28*(1-Math.tanh((T-273)/6))/2)}
function fluxes(){const a=alphaEff(),fin=+solar.value*(1-a)/4,fout=+eps.value*sigma*Math.pow(T,4);return[a,fin,fout,fin-fout]}
function labels(){E('sv').textContent=solar.value+' W/m²';E('av').textContent=alphaEff().toFixed(2);E('ev').textContent=(+eps.value).toFixed(2);E('cv').textContent=cap.value+' arb'}
function step(dt){const [,fin,fout,net]=fluxes(),Ceff=+cap.value*2.4;T+=net/Ceff*dt;t+=dt;hist.push([t,T]);if(hist.length>700)hist.shift()}
function draw(){ctx.fillStyle='#fafaf7';ctx.fillRect(0,0,C.width,C.height);ctx.strokeStyle='#ddd';ctx.beginPath();ctx.moveTo(50,C.height-38);ctx.lineTo(C.width-20,C.height-38);ctx.moveTo(50,20);ctx.lineTo(50,C.height-38);ctx.stroke();const minT=Math.min(230,...hist.map(x=>x[1]))-3,maxT=Math.max(320,...hist.map(x=>x[1]))+3;if(hist.length>1){const t0=hist[0][0],t1=hist.at(-1)[0];ctx.strokeStyle='#d36f52';ctx.lineWidth=3;ctx.beginPath();hist.forEach((p,i)=>{const x=50+(p[0]-t0)/Math.max(1,t1-t0)*(C.width-75),y=C.height-38-(p[1]-minT)/(maxT-minT)*(C.height-65);i?ctx.lineTo(x,y):ctx.moveTo(x,y)});ctx.stroke()}ctx.fillStyle='#666';ctx.font='13px system-ui';ctx.fillText('T (K)',14,28);
 const [a,fin,fout,net]=fluxes();E('temp').textContent=T.toFixed(2)+' K';E('in').textContent=fin.toFixed(1);E('out').textContent=fout.toFixed(1);E('net').textContent=(net>=0?'+':'')+net.toFixed(1);E('av').textContent=a.toFixed(2);
 fc.fillStyle='#fafaf7';fc.fillRect(0,0,F.width,F.height);const max=400,base=F.height-35;for(const [x,val,col,name] of [[180,fin,'#e4aa4f','absorbed SW'],[430,fout,'#6f78d8','outgoing LW'],[680,Math.abs(net),net>=0?'#55aa76':'#d35f58','|net|']]){const h=Math.min(150,val/max*150);fc.fillStyle=col;fc.fillRect(x-55,base-h,110,h);fc.fillStyle='#555';fc.font='13px system-ui';fc.textAlign='center';fc.fillText(name,x,base+18);fc.fillText(val.toFixed(1),x,base-h-8)}}
function loop(now){const dt=Math.min(.05,(now-last)/1000)*5;last=now;if(!paused)step(dt);draw();requestAnimationFrame(loop)}
[solar,albedo,eps,cap].forEach(x=>x.oninput=labels);ice.onchange=labels;E('pause').onclick=()=>{paused=!paused;E('pause').textContent=paused?'Devam et':'Duraklat'};E('reset').onclick=()=>{T=288;t=0;hist=[]};labels();requestAnimationFrame(loop);