const E=id=>document.getElementById(id),O=E('orbit'),oc=O.getContext('2d'),R=E('radius'),rc=R.getContext('2d'),r0=E('r0'),vt=E('vt'),vr=E('vr'),speed=E('speed');
window.mathFormulas={f1:'\\mathbf F=-\\frac{GMm}{r^3}\\mathbf r',f2:'\\ddot{\\mathbf r}=-\\frac{\\mu}{r^3}\\mathbf r,\\qquad \\mu=G(M+m)\\approx GM',f3:'\\mathbf h=\\mathbf r\\times\\mathbf v,\\qquad \\frac{d\\mathbf h}{dt}=0',f4:'\\varepsilon=\\frac{v^2}{2}-\\frac{\\mu}{r}=\\text{constant}',f5:'v_{circ}=\\sqrt{\\frac{\\mu}{r}},\\qquad v_{esc}=\\sqrt{\\frac{2\\mu}{r}}',f6:'e=\\sqrt{1+\\frac{2\\varepsilon h^2}{\\mu^2}}'};
const mu=1;let s,trace,hist,last=performance.now(),paused=false;
function acc(x,y){const r=Math.hypot(x,y),q=-mu/(r*r*r);return[q*x,q*y]}
function init(){const r=+r0.value,vc=Math.sqrt(mu/r);s={x:r,y:0,vx:+vr.value*vc,vy:+vt.value*vc,t:0};trace=[[s.x,s.y]];hist=[[0,r]];last=performance.now();labels()}
function invariants(){const r=Math.hypot(s.x,s.y),v2=s.vx*s.vx+s.vy*s.vy,eps=.5*v2-mu/r,h=s.x*s.vy-s.y*s.vx,e=Math.sqrt(Math.max(0,1+2*eps*h*h/(mu*mu)));return{r,eps,h,e}}
function labels(){const r=+r0.value,vc=Math.sqrt(mu/r),vesc=Math.sqrt(2*mu/r);E('rv').textContent=r.toFixed(2);E('vtv').textContent=(+vt.value).toFixed(2)+'×';E('vrv').textContent=(+vr.value).toFixed(2)+'×';E('sv').textContent=(+speed.value).toFixed(1)+'×';E('vcirc').textContent=vc.toFixed(3);E('vesc').textContent=vesc.toFixed(3);const q=invariants();E('ecc').textContent=q.e.toFixed(3);E('energy').textContent=q.eps.toFixed(4);E('angmom').textContent=q.h.toFixed(4);E('type').textContent=q.eps<-1e-4?(q.e<.03?'dairesel':'eliptik'):q.eps>1e-4?'hiperbolik':'parabol sınırı'}
function step(dt){const n=Math.max(1,Math.ceil(dt/.003)),h=dt/n;for(let i=0;i<n;i++){let a=acc(s.x,s.y);s.x+=s.vx*h+.5*a[0]*h*h;s.y+=s.vy*h+.5*a[1]*h*h;let a2=acc(s.x,s.y);s.vx+=.5*(a[0]+a2[0])*h;s.vy+=.5*(a[1]+a2[1])*h;s.t+=h}const rr=Math.hypot(s.x,s.y);trace.push([s.x,s.y]);hist.push([s.t,rr]);if(trace.length>2200)trace.shift();if(hist.length>1000)hist.shift();labels()}
function drawOrbit(){oc.fillStyle='#f8f7f2';oc.fillRect(0,0,O.width,O.height);const maxR=Math.max(1.5,...trace.map(p=>Math.hypot(p[0],p[1]))),scale=Math.min(O.width,O.height)*.42/maxR,cx=O.width/2,cy=O.height/2;oc.strokeStyle='#d8d5cc';oc.beginPath();oc.arc(cx,cy,scale,0,Math.PI*2);oc.stroke();oc.strokeStyle='#6b5bd3';oc.lineWidth=2.5;oc.beginPath();trace.forEach((p,i)=>{const x=cx+p[0]*scale,y=cy-p[1]*scale;if(i)oc.lineTo(x,y);else oc.moveTo(x,y)});oc.stroke();oc.fillStyle='#e2a64a';oc.beginPath();oc.arc(cx,cy,17,0,Math.PI*2);oc.fill();const x=cx+s.x*scale,y=cy-s.y*scale;oc.fillStyle='#25272d';oc.beginPath();oc.arc(x,y,8,0,Math.PI*2);oc.fill();const vscale=45/Math.max(.2,Math.hypot(s.vx,s.vy));oc.strokeStyle='#df6f67';oc.lineWidth=3;oc.beginPath();oc.moveTo(x,y);oc.lineTo(x+s.vx*vscale,y-s.vy*vscale);oc.stroke()}
function drawRadius(){rc.fillStyle='#fafaf7';rc.fillRect(0,0,R.width,R.height);if(hist.length<2)return;const t0=hist[0][0],t1=hist[hist.length-1][0],mx=Math.max(...hist.map(p=>p[1]));rc.strokeStyle='#ddd';rc.beginPath();rc.moveTo(48,R.height-36);rc.lineTo(R.width-18,R.height-36);rc.moveTo(48,18);rc.lineTo(48,R.height-36);rc.stroke();rc.strokeStyle='#4f9a77';rc.lineWidth=2.5;rc.beginPath();hist.forEach((p,i)=>{const x=48+(p[0]-t0)/Math.max(.1,t1-t0)*(R.width-70),y=R.height-36-p[1]/mx*(R.height-60);if(i)rc.lineTo(x,y);else rc.moveTo(x,y)});rc.stroke()}
function loop(now){const dt=Math.min(.035,(now-last)/1000)*+speed.value;last=now;if(!paused)step(dt);drawOrbit();drawRadius();requestAnimationFrame(loop)}
[r0,vt,vr].forEach(el=>el.oninput=init);speed.oninput=labels;E('reset').onclick=init;E('pause').onclick=()=>{paused=!paused;E('pause').textContent=paused?'Devam et':'Duraklat'};init();requestAnimationFrame(loop);