const E=id=>document.getElementById(id),P=E('pop'),pc=P.getContext('2d'),F=E('phase'),fc=F.getContext('2d'),W=E('world'),wc=W.getContext('2d');
const alpha=E('alpha'),beta=E('beta'),gamma=E('gamma'),delta=E('delta'),x0=E('x0'),y0=E('y0');
window.mathFormulas={f1:'\\frac{dx}{dt}=\\alpha x-\\beta xy=x(\\alpha-\\beta y)',f2:'\\frac{dy}{dt}=\\delta xy-\\gamma y=y(\\delta x-\\gamma)',f3:'(x^*,y^*)=\\left(\\frac{\\gamma}{\\delta},\\frac{\\alpha}{\\beta}\\right)',f4:'H(x,y)=\\delta x-\\gamma\\ln x+\\beta y-\\alpha\\ln y=\\text{constant}'};
let data=[];function par(){return{a:+alpha.value,b:+beta.value,g:+gamma.value,d:+delta.value}}
function deriv(x,y){const q=par();return[q.a*x-q.b*x*y,q.d*x*y-q.g*y]}
function reset(){let x=+x0.value,y=+y0.value;data=[[0,x,y]];for(let i=1;i<=1200;i++){const h=.03,q=par(),f=(X,Y)=>[q.a*X-q.b*X*Y,q.d*X*Y-q.g*Y],k1=f(x,y),k2=f(x+k1[0]*h/2,y+k1[1]*h/2),k3=f(x+k2[0]*h/2,y+k2[1]*h/2),k4=f(x+k3[0]*h,y+k3[1]*h);x=Math.max(.001,x+h*(k1[0]+2*k2[0]+2*k3[0]+k4[0])/6);y=Math.max(.001,y+h*(k1[1]+2*k2[1]+2*k3[1]+k4[1])/6);data.push([i*h,x,y])}labels();draw()}
function labels(){const q=par(),d=deriv(+x0.value,+y0.value);E('av').textContent=q.a.toFixed(2);E('bv').textContent=q.b.toFixed(3);E('gv').textContent=q.g.toFixed(2);E('dv').textContent=q.d.toFixed(3);E('xv').textContent=x0.value;E('yv').textContent=y0.value;E('xeq').textContent=(q.g/q.d).toFixed(1);E('yeq').textContent=(q.a/q.b).toFixed(1);E('dx').textContent=d[0].toFixed(2);E('dy').textContent=d[1].toFixed(2)}
function base(c,W,H){c.fillStyle='#fafaf7';c.fillRect(0,0,W,H);c.strokeStyle='#deddd5';c.lineWidth=1;c.beginPath();c.moveTo(48,H-38);c.lineTo(W-18,H-38);c.moveTo(48,20);c.lineTo(48,H-38);c.stroke()}
function draw(){const maxX=Math.max(...data.map(p=>p[1])),maxY=Math.max(...data.map(p=>p[2])),T=data[data.length-1][0];base(pc,P.width,P.height);for(const pair of [[1,'#7865d5'],[2,'#df7f50']]){const idx=pair[0],col=pair[1],m=idx===1?maxX:maxY;pc.strokeStyle=col;pc.lineWidth=2.5;pc.beginPath();data.forEach((p,i)=>{const x=48+p[0]/T*(P.width-70),y=P.height-38-p[idx]/m*(P.height-68);if(i)pc.lineTo(x,y);else pc.moveTo(x,y)});pc.stroke()}
base(fc,F.width,F.height);fc.strokeStyle='#7865d5';fc.lineWidth=2.5;fc.beginPath();data.forEach((p,i)=>{const x=48+p[1]/maxX*(F.width-70),y=F.height-38-p[2]/maxY*(F.height-68);if(i)fc.lineTo(x,y);else fc.moveTo(x,y)});fc.stroke();const q=par(),xe=q.g/q.d,ye=q.a/q.b;fc.setLineDash([5,5]);fc.strokeStyle='#999';fc.beginPath();let vx=48+xe/maxX*(F.width-70);fc.moveTo(vx,20);fc.lineTo(vx,F.height-38);let hy=F.height-38-ye/maxY*(F.height-68);fc.moveTo(48,hy);fc.lineTo(F.width-18,hy);fc.stroke();fc.setLineDash([]);
wc.fillStyle='#f2efe8';wc.fillRect(0,0,W.width,W.height);const sample=data[Math.floor(data.length*.55)],nx=Math.min(120,Math.round(sample[1]*2)),ny=Math.min(90,Math.round(sample[2]*2));for(let i=0;i<nx;i++){wc.fillStyle='#7865d5';wc.beginPath();wc.arc(20+(i*43)%660,20+((i*79)%320),3,0,Math.PI*2);wc.fill()}for(let i=0;i<ny;i++){const x=20+(i*71)%660,y=20+((i*47)%320);wc.fillStyle='#df7f50';wc.beginPath();wc.moveTo(x,y);wc.lineTo(x+7,y+4);wc.lineTo(x,y+8);wc.closePath();wc.fill()}}
[alpha,beta,gamma,delta,x0,y0].forEach(el=>el.oninput=reset);reset();