const E=id=>document.getElementById(id),C=E('plot'),ctx=C.getContext('2d'),fn=E('fn'),eta=E('eta');let p={x:2.5,y:-1.8},trail=[],n=0,auto=false,last=performance.now();
function F(x,y){return fn.value==='bowl'?.5*(4*x*x+y*y):(1-x)*(1-x)+100*(y-x*x)*(y-x*x)}
function G(x,y){return fn.value==='bowl'?[4*x,y]:[-2*(1-x)-400*x*(y-x*x),200*(y-x*x)]}
function range(){return fn.value==='bowl'?[-3,3,-3,3]:[-2,2,-1,3]}
function reset(){p=fn.value==='bowl'?{x:2.5,y:-1.8}:{x:-1.5,y:2};trail=[[p.x,p.y]];n=0;ui()}
function ui(){const g=G(p.x,p.y),m=Math.hypot(...g);E('etav').textContent=Math.pow(10,+eta.value).toFixed(4);E('fv').textContent=F(p.x,p.y).toFixed(4);E('gv').textContent=m.toFixed(4);E('nv').textContent=n;E('state').textContent=m<1e-3?'yakınsad':Number.isFinite(F(p.x,p.y))&&Math.abs(p.x)<1e4?'çalışıyor':'dağıldı'}
function step(){const g=G(p.x,p.y),lr=Math.pow(10,+eta.value);p.x-=lr*g[0];p.y-=lr*g[1];trail.push([p.x,p.y]);if(trail.length>500)trail.shift();n++;ui()}
function map(x,y){const [xmin,xmax,ymin,ymax]=range();return[50+(x-xmin)/(xmax-xmin)*(C.width-75),C.height-40-(y-ymin)/(ymax-ymin)*(C.height-65)]}
function inv(px,py){const [xmin,xmax,ymin,ymax]=range();return[xmin+(px-50)/(C.width-75)*(xmax-xmin),ymin+(C.height-40-py)/(C.height-65)*(ymax-ymin)]}
function draw(){ctx.fillStyle='#fafaf7';ctx.fillRect(0,0,C.width,C.height);const [xmin,xmax,ymin,ymax]=range(),nx=110,ny=65;let min=Infinity,max=-Infinity,vals=[];for(let j=0;j<ny;j++){vals[j]=[];for(let i=0;i<nx;i++){let x=xmin+(i+.5)/nx*(xmax-xmin),y=ymin+(j+.5)/ny*(ymax-ymin),z=Math.log1p(F(x,y));vals[j][i]=z;min=Math.min(min,z);max=Math.max(max,z)}}for(let j=0;j<ny;j++)for(let i=0;i<nx;i++){const z=(vals[j][i]-min)/(max-min+1e-9),g=Math.round(245-115*z);ctx.fillStyle=`rgb(${g},${g+Math.round(8*(1-z))},${245-Math.round(35*z)})`;ctx.fillRect(50+i/nx*(C.width-75),25+j/ny*(C.height-65),(C.width-75)/nx+1,(C.height-65)/ny+1)}
 if(trail.length>1){ctx.strokeStyle='#6f5bd3';ctx.lineWidth=3;ctx.beginPath();trail.forEach((q,i)=>{const m=map(q[0],q[1]);i?ctx.lineTo(...m):ctx.moveTo(...m)});ctx.stroke()}
 const [px,py]=map(p.x,p.y),g=G(p.x,p.y),gm=Math.hypot(...g)||1;ctx.fillStyle='#1f2228';ctx.beginPath();ctx.arc(px,py,8,0,Math.PI*2);ctx.fill();ctx.strokeStyle='#df6f58';ctx.lineWidth=3;ctx.beginPath();ctx.moveTo(px,py);ctx.lineTo(px-g[0]/gm*55,py+g[1]/gm*55);ctx.stroke()}
C.onclick=e=>{const r=C.getBoundingClientRect(),x=(e.clientX-r.left)*C.width/r.width,y=(e.clientY-r.top)*C.height/r.height,[gx,gy]=inv(x,y);p={x:gx,y:gy};trail=[[gx,gy]];n=0;ui()};E('step').onclick=step;E('auto').onclick=()=>{auto=!auto;E('auto').textContent=auto?'Durdur':'Otomatik'};E('reset').onclick=reset;fn.onchange=reset;eta.oninput=ui;function loop(now){if(auto&&now-last>90){step();last=now}draw();requestAnimationFrame(loop)}reset();requestAnimationFrame(loop);